### ISSUE TITLE
I use this frameworks to tabbar controller, but it occurs segments button index error

### ISSUE THREAD

**Issue by chojunyng** [subinspathilettu/SJSegmentedViewController#23] opened 2016-11-20 14:18 UTC
<img width="1533" alt="2016-11-20 11 16 15" src="https://cloud.githubusercontent.com/assets/8664413/20463485/92abf2ce-af77-11e6-8efd-dab2671ecb51.png">
<img width="578" alt="2016-11-20 11 16 03" src="https://cloud.githubusercontent.com/assets/8664413/20463486/92ac74e2-af77-11e6-9cdb-2991e499a203.png">

**Comment by chojunyng** [comment] 2016-11-20 14:18
how can i fix this error?

**Comment by subinspathilettu** [comment] 2016-11-21 05:51
@chojunyng , Could you please provide some more details about your issue because we were not able to reproduce this issue?

We have updated demo project in the master branch with the tab bar controller and it's working as expected. Could you please check this also.

**Comment by chojunyng** [comment] 2016-11-21 12:10
thank you for your help!
i admire this framework!
but, my project produced swift 2.3 version
can I use it swift 2.3?

**Comment by subinspathilettu** [comment] 2016-11-21 12:40
We upgraded to latest version (Swift 3). If you are on the previous version (Swift 2.3), please use

> pod ’SJSegmentedScrollView’, ‘1.1.0'

**Comment by subinspathilettu** [comment] 2016-11-22 14:28
@chojunyng let me know the status of this issue. Still, you are getting the crash?

**Comment by chojunyng** [comment] 2016-11-22 17:06
yes, it was crushed swift 2.3 version
my app has tab bar with two home SJScrollviews
I think notification center does not notify because this tab bar view does not reload UI
How can i fix it please

**Comment by subinspathilettu** [comment] 2016-11-23 09:55
@chojunyng Resolved in latest version. Please check.

**Closed** 2016-11-25 10:43 UTC

**Comment by chojunyng** [comment] 2016-11-30 23:04
can i fix this issue with a little code in swift 2.3 ?
